const countries = [
    { code: "IN", name: "India", phone: "91", phoneLength: 10 },
    { code: "AD", name: "Andorra", phone: "376", phoneLength: 6 },
    { code: "AE", name: "United Arab Emirates", phone: "971", phoneLength: 9 },
    { code: "AF", name: "Afghanistan", phone: "93", phoneLength: 9 },
    {
      code: "AG",
      name: "Antigua and Barbuda",
      phone: "1-268",
      phoneLength: 10,
    },
    { code: "AI", name: "Anguilla", phone: "1-264", phoneLength: 10 },
    { code: "AL", name: "Albania", phone: "355", phoneLength: 9 },
    { code: "AM", name: "Armenia", phone: "374", phoneLength: 6 },
    { code: "AO", name: "Angola", phone: "244", phoneLength: 9 },
    { code: "AQ", name: "Antarctica", phone: "672", phoneLength: 6 },
    { code: "AR", name: "Argentina", phone: "54", phoneLength: [6, 7, 8] },
    { code: "AS", name: "American Samoa", phone: "1-684", phoneLength: 10 },
    { code: "AT", name: "Austria", phone: "43", phoneLength: [10, 11] },
    {
      code: "AU",
      name: "Australia",
      phone: "61",
      suggested: true,
      phoneLength: 9,
    },
    { code: "AW", name: "Aruba", phone: "297", phoneLength: 7 },
    { code: "AX", name: "Alland Islands", phone: "358", min: 7, max: 10 },
    { code: "AZ", name: "Azerbaijan", phone: "994", phoneLength: 9 },
    {
      code: "BA",
      name: "Bosnia and Herzegovina",
      phone: "387",
      phoneLength: 8,
    },
    { code: "BB", name: "Barbados", phone: "1-246", phoneLength: 10 },
    { code: "BD", name: "Bangladesh", phone: "880", phoneLength: 10 },
    { code: "BE", name: "Belgium", phone: "32", phoneLength: 9 },
    { code: "BF", name: "Burkina Faso", phone: "226", phoneLength: 8 },
    { code: "BG", name: "Bulgaria", phone: "359", phoneLength: 9 },
    { code: "BH", name: "Bahrain", phone: "973", phoneLength: 8 },
    { code: "BI", name: "Burundi", phone: "257", phoneLength: 8 },
    { code: "BJ", name: "Benin", phone: "229", phoneLength: 8 },
    { code: "BL", name: "Saint Barthelemy", phone: "590", phoneLength: 9 },
    { code: "BM", name: "Bermuda", phone: "1-441", phoneLength: 10 },
    { code: "BN", name: "Brunei Darussalam", phone: "673", phoneLength: 7 },
    { code: "BO", name: "Bolivia", phone: "591", phoneLength: 9 },
    { code: "BR", name: "Brazil", phone: "55", phoneLength: 11 },
    { code: "BS", name: "Bahamas", phone: "1-242", phoneLength: 10 },
    { code: "BT", name: "Bhutan", phone: "975", phoneLength: 7 },
    { code: "BV", name: "Bouvet Island", phone: "47", phoneLength: 10 },
    { code: "BW", name: "Botswana", phone: "267", phoneLength: 7 },
    { code: "BY", name: "Belarus", phone: "375", phoneLength: 9 },
    { code: "BZ", name: "Belize", phone: "501", phoneLength: 7 },
    {
      code: "CA",
      name: "Canada",
      phone: "1",
      suggested: true,
      phoneLength: 10,
    },
    {
      code: "CC",
      name: "Cocos (Keeling) Islands",
      phone: "61",
      phoneLength: 10,
    },
    {
      code: "CD",
      name: "Congo, Democratic Republic of the",
      phone: "243",
      phoneLength: 7,
    },
    {
      code: "CF",
      name: "Central African Republic",
      phone: "236",
      phoneLength: 8,
    },
    {
      code: "CG",
      name: "Congo, Republic of the",
      phone: "242",
      phoneLength: 9,
    },
    { code: "CH", name: "Switzerland", phone: "41", phoneLength: 9 },
    { code: "CI", name: "Cote d'Ivoire", phone: "225", phoneLength: 8 },
    { code: "CK", name: "Cook Islands", phone: "682", phoneLength: 5 },
    { code: "CL", name: "Chile", phone: "56", phoneLength: 9 },
    { code: "CM", name: "Cameroon", phone: "237", phoneLength: 9 },
    { code: "CN", name: "China", phone: "86", phoneLength: 11 },
    { code: "CO", name: "Colombia", phone: "57", phoneLength: 10 },
    { code: "CR", name: "Costa Rica", phone: "506", phoneLength: 8 },
    { code: "CU", name: "Cuba", phone: "53", phoneLength: 8 },
    { code: "CV", name: "Cape Verde", phone: "238", phoneLength: 7 },
    { code: "CW", name: "Curacao", phone: "599", phoneLength: 7 },
    { code: "CX", name: "Christmas Island", phone: "61", phoneLength: 9 },
    { code: "CY", name: "Cyprus", phone: "357", phoneLength: 8 },
    { code: "CZ", name: "Czech Republic", phone: "420", phoneLength: 9 },
    {
      code: "DE",
      name: "Germany",
      phone: "49",
      suggested: true,
      phoneLength: 10,
    },
    { code: "DJ", name: "Djibouti", phone: "253", phoneLength: 10 },
    { code: "DK", name: "Denmark", phone: "45", phoneLength: 8 },
    { code: "DM", name: "Dominica", phone: "1-767", phoneLength: 10 },
    { code: "DO", name: "Dominican Republic", phone: "1-809", phoneLength: 10 },
    { code: "DZ", name: "Algeria", phone: "213", phoneLength: 9 },
    { code: "EC", name: "Ecuador", phone: "593", phoneLength: 9 },
    { code: "EE", name: "Estonia", phone: "372", phoneLength: 8 },
    { code: "EG", name: "Egypt", phone: "20", phoneLength: 10 },
    { code: "EH", name: "Western Sahara", phone: "212", phoneLength: 9 },
    { code: "ER", name: "Eritrea", phone: "291", phoneLength: 7 },
    { code: "ES", name: "Spain", phone: "34", phoneLength: 9 },
    { code: "ET", name: "Ethiopia", phone: "251", phoneLength: 9 },
    { code: "FI", name: "Finland", phone: "358", min: 9, max: 11 },
    { code: "FJ", name: "Fiji", phone: "679", phoneLength: 7 },
    {
      code: "FK",
      name: "Falkland Islands (Malvinas)",
      phone: "500",
      phoneLength: 5,
    },
    {
      code: "FM",
      name: "Micronesia, Federated States of",
      phone: "691",
      phoneLength: 7,
    },
    { code: "FO", name: "Faroe Islands", phone: "298", phoneLength: 5 },
    {
      code: "FR",
      name: "France",
      phone: "33",
      suggested: true,
      phoneLength: 9,
    },
    { code: "GA", name: "Gabon", phone: "241", phoneLength: 7 },
    { code: "GB", name: "United Kingdom", phone: "44", phoneLength: 10 },
    { code: "GD", name: "Grenada", phone: "1-473", phoneLength: 10 },
    { code: "GE", name: "Georgia", phone: "995", phoneLength: 9 },
    { code: "GF", name: "French Guiana", phone: "594", phoneLength: 9 },
    { code: "GG", name: "Guernsey", phone: "44", phoneLength: 10 },
    { code: "GH", name: "Ghana", phone: "233", phoneLength: 9 },
    { code: "GI", name: "Gibraltar", phone: "350", phoneLength: 8 },
    { code: "GL", name: "Greenland", phone: "299", phoneLength: 6 },
    { code: "GM", name: "Gambia", phone: "220", phoneLength: 7 },
    { code: "GN", name: "Guinea", phone: "224", phoneLength: 9 },
    { code: "GP", name: "Guadeloupe", phone: "590", phoneLength: 9 },
    { code: "GQ", name: "Equatorial Guinea", phone: "240", phoneLength: 9 },
    { code: "GR", name: "Greece", phone: "30", phoneLength: 10 },
    {
      code: "GS",
      name: "South Georgia and the South Sandwich Islands",
      phone: "500",
      phoneLength: 5,
    },
    { code: "GT", name: "Guatemala", phone: "502", phoneLength: 8 },
    { code: "GU", name: "Guam", phone: "1-671", phoneLength: 10 },
    { code: "GW", name: "Guinea-Bissau", phone: "245", phoneLength: 9 },
    { code: "GY", name: "Guyana", phone: "592", phoneLength: 7 },
    { code: "HK", name: "Hong Kong", phone: "852", phoneLength: 8 },
    {
      code: "HM",
      name: "Heard Island and McDonald Islands",
      phone: "672",
      phoneLength: 10,
    },
    { code: "HN", name: "Honduras", phone: "504", phoneLength: 8 },
    { code: "HR", name: "Croatia", phone: "385", phoneLength: 9 },
    { code: "HT", name: "Haiti", phone: "509", phoneLength: 8 },
    { code: "HU", name: "Hungary", phone: "36", phoneLength: 9 },
    { code: "ID", name: "Indonesia", phone: "62", phoneLength: 11 },
    { code: "IE", name: "Ireland", phone: "353", phoneLength: 9 },
    { code: "IL", name: "Israel", phone: "972", phoneLength: 9 },
    { code: "IM", name: "Isle of Man", phone: "44", phoneLength: 10 },
    {
      code: "IO",
      name: "British Indian Ocean Territory",
      phone: "246",
      phoneLength: 7,
    },
    { code: "IQ", name: "Iraq", phone: "964", phoneLength: 10 },
    {
      code: "IR",
      name: "Iran, Islamic Republic of",
      phone: "98",
      phoneLength: 11,
    },
    { code: "IS", name: "Iceland", phone: "354", phoneLength: 7 },
    { code: "IT", name: "Italy", phone: "39", phoneLength: 10 },
    { code: "JE", name: "Jersey", phone: "44", phoneLength: 10 },
    { code: "JM", name: "Jamaica", phone: "1-876", phoneLength: 10 },
    { code: "JO", name: "Jordan", phone: "962", phoneLength: [8, 9] },
    { code: "JP", name: "Japan", phone: "81", suggested: true },
    { code: "KE", name: "Kenya", phone: "254", phoneLength: 10 },
    { code: "KG", name: "Kyrgyzstan", phone: "996", phoneLength: 9 },
    { code: "KH", name: "Cambodia", phone: "855", phoneLength: 9 },
    { code: "KI", name: "Kiribati", phone: "686", phoneLength: 8 },
    { code: "KM", name: "Comoros", phone: "269", phoneLength: 7 },
    {
      code: "KN",
      name: "Saint Kitts and Nevis",
      phone: "1-869",
      phoneLength: 10,
    },
    {
      code: "KP",
      name: "Korea, Democratic People's Republic of",
      phone: "850",
      phoneLength: [4, 6, 7, 13],
    },
    {
      code: "KR",
      name: "Korea, Republic of",
      phone: "82",
      phoneLength: [7, 8],
    },
    { code: "KW", name: "Kuwait", phone: "965", phoneLength: 8 },
    { code: "KY", name: "Cayman Islands", phone: "1-345", phoneLength: 7 },
    { code: "KZ", name: "Kazakhstan", phone: "7", phoneLength: 10 },
    {
      code: "LA",
      name: "Lao People's Democratic Republic",
      phone: "856",
      phoneLength: [8, 9],
    },
    { code: "LB", name: "Lebanon", phone: "961", phoneLength: [7, 8] },
    { code: "LC", name: "Saint Lucia", phone: "1-758", phoneLength: 7 },
    { code: "LI", name: "Liechtenstein", phone: "423", phoneLength: 7 },
    { code: "LK", name: "Sri Lanka", phone: "94", phoneLength: 7 },
    { code: "LR", name: "Liberia", phone: "231", phoneLength: [8, 9] },
    { code: "LS", name: "Lesotho", phone: "266", phoneLength: 8 },
    { code: "LT", name: "Lithuania", phone: "370", phoneLength: 8 },
    { code: "LU", name: "Luxembourg", phone: "352", phoneLength: 9 },
    { code: "LV", name: "Latvia", phone: "371", phoneLength: 8 },
    { code: "LY", name: "Libya", phone: "218", phoneLength: 10 },
    { code: "MA", name: "Morocco", phone: "212", phoneLength: 9 },
    { code: "MC", name: "Monaco", phone: "377", phoneLength: 8 },
    { code: "MD", name: "Moldova, Republic of", phone: "373", phoneLength: 8 },
    { code: "ME", name: "Montenegro", phone: "382", phoneLength: 8 },
    {
      code: "MF",
      name: "Saint Martin (French part)",
      phone: "590",
      phoneLength: 6,
    },
    { code: "MG", name: "Madagascar", phone: "261", phoneLength: 7 },
    { code: "MH", name: "Marshall Islands", phone: "692", phoneLength: 7 },
    {
      code: "MK",
      name: "Macedonia, the Former Yugoslav Republic of",
      phone: "389",
      phoneLength: 8,
    },
    { code: "ML", name: "Mali", phone: "223", phoneLength: 8 },
    { code: "MM", name: "Myanmar", phone: "95", min: 7, max: 10 },
    { code: "MN", name: "Mongolia", phone: "976", phoneLength: 8 },
    { code: "MO", name: "Macao", phone: "853", phoneLength: 8 },
    {
      code: "MP",
      name: "Northern Mariana Islands",
      phone: "1-670",
      phoneLength: 7,
    },
    { code: "MQ", name: "Martinique", phone: "596", phoneLength: 9 },
    { code: "MR", name: "Mauritania", phone: "222", phoneLength: 8 },
    { code: "MS", name: "Montserrat", phone: "1-664", phoneLength: 10 },
    { code: "MT", name: "Malta", phone: "356", phoneLength: 8 },
    { code: "MU", name: "Mauritius", phone: "230", phoneLength: 8 },
    { code: "MV", name: "Maldives", phone: "960", phoneLength: 7 },
    { code: "MW", name: "Malawi", phone: "265", phoneLength: [7, 8, 9] },
    { code: "MX", name: "Mexico", phone: "52", phoneLength: 10 },
    { code: "MY", name: "Malaysia", phone: "60", phoneLength: 7 },
    { code: "MZ", name: "Mozambique", phone: "258", phoneLength: 12 },
    { code: "NA", name: "Namibia", phone: "264", phoneLength: 7 },
    { code: "NC", name: "New Caledonia", phone: "687", phoneLength: 6 },
    { code: "NE", name: "Niger", phone: "227", phoneLength: 8 },
    { code: "NF", name: "Norfolk Island", phone: "672", phoneLength: 6 },
    { code: "NG", name: "Nigeria", phone: "234", phoneLength: 8 },
    { code: "NI", name: "Nicaragua", phone: "505", phoneLength: 8 },
    { code: "NL", name: "Netherlands", phone: "31", phoneLength: 9 },
    { code: "NO", name: "Norway", phone: "47", phoneLength: 8 },
    { code: "NP", name: "Nepal", phone: "977", phoneLength: 10 },
    { code: "NR", name: "Nauru", phone: "674", phoneLength: 7 },
    { code: "NU", name: "Niue", phone: "683", phoneLength: 4 },
    { code: "NZ", name: "New Zealand", phone: "64", phoneLength: [8, 9] },
    { code: "OM", name: "Oman", phone: "968", phoneLength: 8 },
    { code: "PA", name: "Panama", phone: "507", phoneLength: 8 },
    { code: "PE", name: "Peru", phone: "51", phoneLength: 9 },
    { code: "PF", name: "French Polynesia", phone: "689", phoneLength: 8 },
    { code: "PG", name: "Papua New Guinea", phone: "675", phoneLength: 8 },
    { code: "PH", name: "Philippines", phone: "63", phoneLength: 10 },
    { code: "PK", name: "Pakistan", phone: "92", phoneLength: 10 },
    { code: "PL", name: "Poland", phone: "48", phoneLength: 9 },
    {
      code: "PM",
      name: "Saint Pierre and Miquelon",
      phone: "508",
      phoneLength: 6,
    },
    { code: "PN", name: "Pitcairn", phone: "870", phoneLength: 9 },
    { code: "PR", name: "Puerto Rico", phone: "1", phoneLength: 10 },
    { code: "PS", name: "Palestine, State of", phone: "970", phoneLength: 9 },
    { code: "PT", name: "Portugal", phone: "351", phoneLength: 9 },
    { code: "PW", name: "Palau", phone: "680", phoneLength: 7 },
    { code: "PY", name: "Paraguay", phone: "595", phoneLength: 9 },
    { code: "QA", name: "Qatar", phone: "974", phoneLength: 8 },
    { code: "RE", name: "Reunion", phone: "262", phoneLength: 10 },
    { code: "RO", name: "Romania", phone: "40", phoneLength: 10 },
    { code: "RS", name: "Serbia", phone: "381", phoneLength: 9 },
    { code: "RU", name: "Russian Federation", phone: "7", phoneLength: 10 },
    { code: "RW", name: "Rwanda", phone: "250", phoneLength: 9 },
    { code: "SA", name: "Saudi Arabia", phone: "966", phoneLength: 9 },
    { code: "SB", name: "Solomon Islands", phone: "677", phoneLength: 7 },
    { code: "SC", name: "Seychelles", phone: "248", phoneLength: 7 },
    { code: "SD", name: "Sudan", phone: "249", phoneLength: 7 },
    { code: "SE", name: "Sweden", phone: "46", phoneLength: 7 },
    { code: "SG", name: "Singapore", phone: "65", phoneLength: 8 },
    { code: "SH", name: "Saint Helena", phone: "290", phoneLength: 4 },
    { code: "SI", name: "Slovenia", phone: "386", phoneLength: 9 },
    { code: "SJ", name: "Svalbard and Jan Mayen", phone: "47", phoneLength: 8 },
    { code: "SK", name: "Slovakia", phone: "421", phoneLength: 9 },
    { code: "SL", name: "Sierra Leone", phone: "232", phoneLength: 8 },
    { code: "SM", name: "San Marino", phone: "378", phoneLength: 10 },
    { code: "SN", name: "Senegal", phone: "221", phoneLength: 9 },
    { code: "SO", name: "Somalia", phone: "252", phoneLength: [8, 9] },
    { code: "SR", name: "Suriname", phone: "597", phoneLength: [6, 7] },
    { code: "SS", name: "South Sudan", phone: "211", phoneLength: 7 },
    { code: "ST", name: "Sao Tome and Principe", phone: "239", phoneLength: 7 },
    { code: "SV", name: "El Salvador", phone: "503", phoneLength: 8 },
    {
      code: "SX",
      name: "Sint Maarten (Dutch part)",
      phone: "1-721",
      phoneLength: 10,
    },
    { code: "SY", name: "Syrian Arab Republic", phone: "963", phoneLength: 7 },
    { code: "SZ", name: "Swaziland", phone: "268", phoneLength: 8 },
    {
      code: "TC",
      name: "Turks and Caicos Islands",
      phone: "1-649",
      phoneLength: 10,
    },
    { code: "TD", name: "Chad", phone: "235", phoneLength: 6 },
    {
      code: "TF",
      name: "French Southern Territories",
      phone: "262",
      phoneLength: 10,
    },
    { code: "TG", name: "Togo", phone: "228", phoneLength: 8 },
    { code: "TH", name: "Thailand", phone: "66", phoneLength: 9 },
    { code: "TJ", name: "Tajikistan", phone: "992", phoneLength: 9 },
    { code: "TK", name: "Tokelau", phone: "690", phoneLength: 5 },
    { code: "TL", name: "Timor-Leste", phone: "670", phoneLength: 7 },
    { code: "TM", name: "Turkmenistan", phone: "993", phoneLength: 8 },
    { code: "TN", name: "Tunisia", phone: "216", phoneLength: 8 },
    { code: "TO", name: "Tonga", phone: "676", phoneLength: 5 },
    { code: "TR", name: "Turkey", phone: "90", phoneLength: 11 },
    { code: "TT", name: "Trinidad and Tobago", phone: "1-868", phoneLength: 7 },
    { code: "TV", name: "Tuvalu", phone: "688", phoneLength: 5 },
    {
      code: "TW",
      name: "Taiwan, Province of China",
      phone: "886",
      phoneLength: 9,
    },
    {
      code: "TZ",
      name: "United Republic of Tanzania",
      phone: "255",
      phoneLength: 7,
    },
    { code: "UA", name: "Ukraine", phone: "380", phoneLength: 9 },
    { code: "UG", name: "Uganda", phone: "256", phoneLength: 7 },
    {
      code: "US",
      name: "United States",
      phone: "1",
      suggested: true,
      phoneLength: 10,
    },
    { code: "UY", name: "Uruguay", phone: "598", phoneLength: 8 },
    { code: "UZ", name: "Uzbekistan", phone: "998", phoneLength: 9 },
    {
      code: "VA",
      name: "Holy See (Vatican City State)",
      phone: "379",
      phoneLength: 10,
    },
    {
      code: "VC",
      name: "Saint Vincent and the Grenadines",
      phone: "1-784",
      phoneLength: 7,
    },
    { code: "VE", name: "Venezuela", phone: "58", phoneLength: 7 },
    {
      code: "VG",
      name: "British Virgin Islands",
      phone: "1-284",
      phoneLength: 7,
    },
    { code: "VI", name: "US Virgin Islands", phone: "1-340", phoneLength: 10 },
    { code: "VN", name: "Vietnam", phone: "84", phoneLength: 9 },
    { code: "VU", name: "Vanuatu", phone: "678", phoneLength: 5 },
    { code: "WF", name: "Wallis and Futuna", phone: "681", phoneLength: 6 },
    { code: "WS", name: "Samoa", phone: "685", phoneLength: [5, 6, 7] },
    { code: "XK", name: "Kosovo", phone: "383", phoneLength: 8 },
    { code: "YE", name: "Yemen", phone: "967", phoneLength: 9 },
    { code: "YT", name: "Mayotte", phone: "262", phoneLength: 9 },
    { code: "ZA", name: "South Africa", phone: "27", phoneLength: 9 },
    { code: "ZM", name: "Zambia", phone: "260", phoneLength: 9 },
    { code: "ZW", name: "Zimbabwe", phone: "263", phoneLength: 9 },
  ];

  export default countries